server:
  port: 8887

# 需指明，服务和服务之间相互调用一般根据该name
spring:
  application:
    name: provider
  security:
    basic:
      enabled: true # 启用SpringSecurity的安全配置项
    user:
      name: admin
      password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

